version: "2.1"
services:
  krakend-framework:
    build: ${PWD}/api-gateway/krakend-framework
    image: tmp/krakend-framework
    ports:
      - "9104:8080"
    volumes:
      - ${PWD}/api-gateway/krakend-service/krakend.json:/etc/krakend/krakend.json:ro