version: "2.1"
services:
  api-json:
    image: nginx:1.19.6
    ports:
      - "9001:80"
    volumes:
      - ${PWD}/raw-servers/volume-data/json/:/etc/nginx/html:ro
      - ${PWD}/raw-servers/nginx.conf:/etc/nginx/nginx.conf:ro
  api-xml:
    image: nginx:1.19.6
    ports:
      - "9002:80"
    volumes:
      - ${PWD}/raw-servers/volume-data/xml/:/etc/nginx/html:ro
      - ${PWD}/raw-servers/nginx.conf:/etc/nginx/nginx.conf:ro
  api-pdf:
    image: nginx:1.19.6
    ports:
      - "9003:80"
    volumes:
      - ${PWD}/raw-servers/volume-data/pdf/:/etc/nginx/html:ro
      - ${PWD}/raw-servers/nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16